name: xeus-ruby
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus-zmq >=1.0.2,<2.0
  - nlohmann_json
  - cppzmq
  - xtl
  - jupyterlab
  - ruby >=3.2
  # Test dependencies
  - pytest
  - jupyter_kernel_test
  - nbval
  - pytest-rerunfailures
