[project]
name = "xeus-ruby"
version = "0.1.0"
description = "Add a short description here"
authors = ["isabel.paredes@quantstack.net"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
start = { cmd = "cd notebooks/; jupyter lab", depends_on = ["build"] }

[dependencies]
# xeus-ruby = "0.1.0"
ipywidgets = ">=8.0"
jupyterlab = "*"

[feature.dev.dependencies]
ninja = "*"
cmake = "*"
cxx-compiler = "*"
# Host dependencies
xeus-zmq = ">=1.0.2,<2.0"
nlohmann_json = "*"
cppzmq = "*"
xtl = "*"
ruby = ">=3.2"
rice = "*"
# Test dependencies
pytest = "*"
jupyter_kernel_test = "*"
nbval = "*"
pytest-rerunfailures = "*"

[feature.dev.tasks]
build = """
    mkdir -p build;
    cd build;
    cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -GNinja;
    ninja;
    ninja install;
"""

[feature.wasm-host]
channels = ["https://repo.mamba.pm/emscripten-forge", "conda-forge"]
platforms = ["emscripten-wasm32"]

[feature.wasm-host.dependencies]
nlohmann_json = "*"
xeus-lite = "*"
xeus = ">=3.0.5,<4.0"
xtl = ">=0.7,<0.8"


[environments]
default = ["dev"]
dev = ["dev"]
wasm-host = ["wasm-host"]
